#!/usr/bin/env python3
"""Validate the constrained repository shape generated by this template.

This is deliberately not a general YAML parser. It recognizes only the top-level
sections, two-space scalar fields, and JSON-compatible inline arrays emitted by
``init_repository.py``. Expanding the generated YAML shape requires updating this
validator and its tests together.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
from typing import Any, Iterable, Sequence

from init_repository import (
    DATA_CLASSIFICATIONS,
    PLACEHOLDER_PATTERN,
    PROJECT_ID_PATTERN,
    PROJECT_STATUSES,
    PROJECT_TEMPLATE_PLACEHOLDERS,
    PROJECT_TYPES,
    README_TEMPLATE_PLACEHOLDERS,
    VISIBILITIES,
    repository_root,
)


REQUIRED_FILES = (
    ".ephy/project.yaml",
    ".ephy/project.template.yaml",
    ".ephy/schema/project.schema.json",
    ".github/ISSUE_TEMPLATE/bug.yml",
    ".github/ISSUE_TEMPLATE/feature.yml",
    ".github/ISSUE_TEMPLATE/design.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/pull_request_template.md",
    ".github/workflows/validate-template.yml",
    "docs/architecture.md",
    "docs/repository-relations.md",
    "docs/security-and-data.md",
    "docs/adr/README.md",
    "docs/adr/0000-template.md",
    "scripts/init_repository.py",
    "scripts/validate_repository.py",
    "tests/test_init_repository.py",
    "tests/test_validate_repository.py",
    "AGENTS.md",
    "README.md",
    "README.template.md",
    "CHANGELOG.md",
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
)

REQUIRED_README_SECTIONS = (
    "Overview",
    "Role in the Ephy ecosystem",
    "Goals",
    "Non-goals",
    "Current status",
    "Architecture",
    "Repository relationships",
    "Getting started",
    "Testing",
    "Security and data handling",
    "Documentation",
    "License",
)

EXPECTED_SECTIONS = {
    "project": {"id", "family", "type", "status", "visibility", "description"},
    "relations": {"parent", "depends_on", "integrates_with", "runs_on"},
    "data_policy": {
        "classification",
        "personal_data_in_git",
        "secrets_in_git",
    },
}

ALLOWED_TEMPLATE_PLACEHOLDERS = {
    ".ephy/project.template.yaml": PROJECT_TEMPLATE_PLACEHOLDERS,
    "README.template.md": README_TEMPLATE_PLACEHOLDERS,
}

# The initializer necessarily names the same fixed tokens in its replacement
# tables. They are intentional there，but unlike template files they are not
# required as a completeness contract for general text scanning.
ALLOWED_CODE_PLACEHOLDERS = {
    "scripts/init_repository.py": (
        PROJECT_TEMPLATE_PLACEHOLDERS | README_TEMPLATE_PLACEHOLDERS
    )
}

SENSITIVE_PATTERNS = {
    "AWS access key": re.compile(r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b"),
    "GitHub token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b"),
    "OpenAI-style secret": re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
    "Google API key": re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b"),
    "Slack token": re.compile(r"\bxox[baprs]-[0-9A-Za-z-]{20,}\b"),
    "PEM private key": re.compile(
        r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"
    ),
}


def parse_value(raw: str) -> Any:
    """Parse only JSON-style values or simple unquoted YAML scalars."""
    raw = raw.strip()
    if not raw:
        raise ValueError("value is empty")
    if raw[0] in '["' or raw in {"true", "false", "null"} or raw.isdigit():
        return json.loads(raw)
    if any(character in raw for character in ("#", "[", "]", "{", "}")):
        raise ValueError("unsupported unquoted scalar")
    return raw


def parse_metadata(text: str) -> tuple[dict[str, dict[str, Any]], list[str]]:
    """Parse the fixed metadata layout and return data plus structural errors."""
    errors: list[str] = []
    sections: dict[str, dict[str, Any]] = {}
    schema_version: Any = None
    current_section: str | None = None

    for line_number, line in enumerate(text.splitlines(), start=1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if "\t" in line:
            errors.append(f"project.yaml:{line_number}: tabs are not supported")
            continue
        schema_match = re.fullmatch(r"schema_version:\s*(.+)", line)
        if schema_match:
            if schema_version is not None:
                errors.append("project.yaml: duplicate schema_version")
            try:
                schema_version = parse_value(schema_match.group(1))
            except (ValueError, json.JSONDecodeError) as exc:
                errors.append(f"project.yaml:{line_number}: invalid schema_version: {exc}")
            current_section = None
            continue
        section_match = re.fullmatch(r"([a-z_]+):\s*", line)
        if section_match:
            current_section = section_match.group(1)
            if current_section in sections:
                errors.append(f"project.yaml: duplicate section {current_section}")
            sections.setdefault(current_section, {})
            continue
        field_match = re.fullmatch(r"  ([a-z_]+):\s*(.+)", line)
        if field_match and current_section is not None:
            key, raw = field_match.groups()
            if key in sections[current_section]:
                errors.append(
                    f"project.yaml:{line_number}: duplicate field {current_section}.{key}"
                )
                continue
            try:
                sections[current_section][key] = parse_value(raw)
            except (ValueError, json.JSONDecodeError) as exc:
                errors.append(
                    f"project.yaml:{line_number}: invalid {current_section}.{key}: {exc}"
                )
            continue
        errors.append(f"project.yaml:{line_number}: unsupported YAML structure")

    if schema_version != 1:
        errors.append("project.yaml: schema_version must be 1")
    actual_sections = set(sections)
    expected_sections = set(EXPECTED_SECTIONS)
    for missing in sorted(expected_sections - actual_sections):
        errors.append(f"project.yaml: missing section {missing}")
    for unexpected in sorted(actual_sections - expected_sections):
        errors.append(f"project.yaml: unexpected section {unexpected}")
    for section, expected_fields in EXPECTED_SECTIONS.items():
        actual_fields = set(sections.get(section, {}))
        for missing in sorted(expected_fields - actual_fields):
            errors.append(f"project.yaml: missing field {section}.{missing}")
        for unexpected in sorted(actual_fields - expected_fields):
            errors.append(f"project.yaml: unexpected field {section}.{unexpected}")
    return sections, errors


def validate_id(value: Any, field: str, errors: list[str]) -> None:
    if not isinstance(value, str) or not PROJECT_ID_PATTERN.fullmatch(value):
        errors.append(f"project.yaml: {field} must be a lowercase kebab-case project ID")


def validate_id_list(value: Any, field: str, errors: list[str]) -> None:
    if not isinstance(value, list):
        errors.append(f"project.yaml: {field} must be an inline list")
        return
    if len(value) != len({item for item in value if isinstance(item, str)}):
        errors.append(f"project.yaml: {field} must not contain duplicates")
    for index, item in enumerate(value):
        validate_id(item, f"{field}[{index}]", errors)


def validate_metadata(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"cannot read {path}: {exc}"]
    sections, errors = parse_metadata(text)
    project = sections.get("project", {})
    relations = sections.get("relations", {})
    data_policy = sections.get("data_policy", {})

    validate_id(project.get("id"), "project.id", errors)
    if project.get("family") != "ephy":
        errors.append("project.yaml: project.family must be ephy")
    if project.get("type") not in PROJECT_TYPES:
        errors.append(f"project.yaml: unsupported project.type {project.get('type')!r}")
    if project.get("status") not in PROJECT_STATUSES:
        errors.append(f"project.yaml: unsupported project.status {project.get('status')!r}")
    if project.get("visibility") not in VISIBILITIES:
        errors.append(
            f"project.yaml: unsupported project.visibility {project.get('visibility')!r}"
        )
    description = project.get("description")
    if not isinstance(description, str) or not description.strip():
        errors.append("project.yaml: project.description must be a non-empty string")

    validate_id(relations.get("parent"), "relations.parent", errors)
    for field in ("depends_on", "integrates_with", "runs_on"):
        validate_id_list(relations.get(field), f"relations.{field}", errors)

    if data_policy.get("classification") not in DATA_CLASSIFICATIONS:
        errors.append(
            "project.yaml: unsupported data_policy.classification "
            f"{data_policy.get('classification')!r}"
        )
    for field in ("personal_data_in_git", "secrets_in_git"):
        if data_policy.get(field) != "prohibited":
            errors.append(f"project.yaml: data_policy.{field} must be prohibited")
    return errors


def iter_text_files(root: Path) -> Iterable[tuple[str, str]]:
    """Yield small UTF-8 text files while excluding VCS and generated caches."""
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        if any(part in {".git", "__pycache__", ".pytest_cache"} for part in relative.parts):
            continue
        try:
            content = path.read_bytes()
        except OSError:
            continue
        if len(content) > 1_000_000 or b"\x00" in content:
            continue
        try:
            yield relative.as_posix(), content.decode("utf-8")
        except UnicodeDecodeError:
            continue


def validate_placeholders(text_files: Sequence[tuple[str, str]]) -> list[str]:
    errors: list[str] = []
    seen_templates: set[str] = set()
    for relative, content in text_files:
        found = set(PLACEHOLDER_PATTERN.findall(content))
        allowed = ALLOWED_TEMPLATE_PLACEHOLDERS.get(
            relative, ALLOWED_CODE_PLACEHOLDERS.get(relative, set())
        )
        if relative in ALLOWED_TEMPLATE_PLACEHOLDERS:
            seen_templates.add(relative)
            missing = allowed - found
            if missing:
                errors.append(f"{relative}: missing expected placeholders {sorted(missing)}")
        unexpected = found - allowed
        if unexpected:
            errors.append(f"{relative}: unexpected placeholders {sorted(unexpected)}")
    for relative in sorted(set(ALLOWED_TEMPLATE_PLACEHOLDERS) - seen_templates):
        errors.append(f"{relative}: template could not be scanned")
    return errors


def validate_readme(path: Path, display_name: str) -> list[str]:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"cannot read {display_name}: {exc}"]
    headings = set(re.findall(r"^## (.+?)\s*$", content, re.MULTILINE))
    return [
        f"{display_name}: missing required section {section!r}"
        for section in REQUIRED_README_SECTIONS
        if section not in headings
    ]


def validate_schema(path: Path) -> list[str]:
    """Check that the checked-in JSON Schema expresses the tooling's enums."""
    try:
        schema = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return [f"project.schema.json: invalid JSON: {exc}"]
    try:
        project = schema["properties"]["project"]["properties"]
        relations = schema["properties"]["relations"]["properties"]
        data_policy = schema["properties"]["data_policy"]["properties"]
        project_id = schema["$defs"]["projectId"]
        project_id_list = schema["$defs"]["projectIdList"]
    except (KeyError, TypeError) as exc:
        return [f"project.schema.json: missing required schema structure: {exc}"]

    errors: list[str] = []
    enum_checks = (
        (project.get("type", {}).get("enum"), PROJECT_TYPES, "project.type"),
        (project.get("status", {}).get("enum"), PROJECT_STATUSES, "project.status"),
        (project.get("visibility", {}).get("enum"), VISIBILITIES, "project.visibility"),
        (
            data_policy.get("classification", {}).get("enum"),
            DATA_CLASSIFICATIONS,
            "data_policy.classification",
        ),
    )
    for actual, expected, field in enum_checks:
        if actual != list(expected):
            errors.append(f"project.schema.json: {field} enum differs from tooling")
    if project_id.get("pattern") != PROJECT_ID_PATTERN.pattern:
        errors.append("project.schema.json: project ID pattern differs from tooling")
    if project_id_list.get("uniqueItems") is not True:
        errors.append("project.schema.json: relationship lists must use uniqueItems")
    for field in ("personal_data_in_git", "secrets_in_git"):
        if data_policy.get(field, {}).get("const") != "prohibited":
            errors.append(f"project.schema.json: data_policy.{field} must be prohibited")
    if set(relations) != {"parent", "depends_on", "integrates_with", "runs_on"}:
        errors.append("project.schema.json: relationship fields differ from tooling")
    return errors


def validate_sensitive_patterns(
    text_files: Sequence[tuple[str, str]],
) -> list[str]:
    errors: list[str] = []
    for relative, content in text_files:
        for label, pattern in SENSITIVE_PATTERNS.items():
            if pattern.search(content):
                errors.append(f"{relative}: contains a value resembling {label}")
    return errors


def validate(root: Path, check_sensitive_patterns: bool = False) -> list[str]:
    errors: list[str] = []
    for relative in REQUIRED_FILES:
        path = root / relative
        if not path.is_file():
            errors.append(f"missing required file: {relative}")
    metadata_path = root / ".ephy" / "project.yaml"
    if metadata_path.is_file():
        errors.extend(validate_metadata(metadata_path))
    readme_path = root / "README.md"
    if readme_path.is_file():
        errors.extend(validate_readme(readme_path, "README.md"))
    readme_template_path = root / "README.template.md"
    if readme_template_path.is_file():
        errors.extend(validate_readme(readme_template_path, "README.template.md"))
    schema_path = root / ".ephy" / "schema" / "project.schema.json"
    if schema_path.is_file():
        errors.extend(validate_schema(schema_path))

    text_files = list(iter_text_files(root))
    errors.extend(validate_placeholders(text_files))
    if check_sensitive_patterns:
        errors.extend(validate_sensitive_patterns(text_files))
    return errors


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validate an Ephy template or initialized repository."
    )
    parser.add_argument(
        "--check-sensitive-patterns",
        action="store_true",
        help="scan text files for common fixed secret formats",
    )
    parser.add_argument("--root", help=argparse.SUPPRESS)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        root = repository_root(args.root)
        errors = validate(root, args.check_sensitive_patterns)
    except (OSError, ValueError) as exc:
        print(f"validation failed: {exc}", file=sys.stderr)
        return 1
    if errors:
        print("Repository validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"Repository validation passed: {root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
